### ISSUE TITLE
Data Processing

### ISSUE THREAD

**Issue by wangyu0627** [HKUDS/RLMRec#10]
Hi, it's a great job. However, I still have a question:
How did you get the files before the prompt generation summary and reason, i.e. the complete document ``generation/user/user_prompt.''
I would like you to show this part of the raw data and look forward to your reply!

**Comment by Re-bin** [comment]
Hi 👋!

Thank you for your interest in RLMRec! We provide links to the raw data and the [mapper information](https://github.com/HKUDS/RLMRec/tree/main/data/mapper) in JSON format, which maps the user and item IDs to their original IDs in the raw datasets.

- **Yelp:** [https://www.yelp.com/dataset](https://www.yelp.com/dataset)
- **Amazon Books:** [https://cseweb.ucsd.edu/~jmcauley/datasets/amazon/links.html](https://cseweb.ucsd.edu/~jmcauley/datasets/amazon/links.html)
- **Steam:** [https://github.com/kang205/SASRec](https://github.com/kang205/SASRec)

With these resources, you can access the raw data used for processing user and item profile generation. Please note that for the review or purchased item information in user/item prompts, the relevant user-item interactions are not included in the validation/test sets to avoid data leakage. I hope this information is helpful to you :)

Best regards,
Xubin

**Comment by wangyu0627** [comment]
Okay, thanks! Have a nice life and good luck with your studies!

**Comment by IIM-D** [comment]
HI, would you explan ” the relevant user-item interactions are not included in the validation/test sets to avoid data leakage“ please? 
Aren't the test set and validation set split from the binary adjacency matrix of user-item interactions based on a certain proportion?
look forward to your reply! 
Best regards!
