### ISSUE TITLE
Relations between "Instruction" and "Input Prompt"

### ISSUE THREAD

**Issue by xmttttt** [HKUDS/RLMRec#3]
Hi! Thanks for your code to generate profiles! I'd like to further ask that when you used the OpenAI API, did you concatenate the instruction before each input prompt?
for example:
    [instruction, input1] ->gpt-> output1
    [instruction, intput2] ->gpt-> output2
    ...
(isn't that a little expensive qaq)

Also, may I ask if you can provide the preprocessing code from the raw dataset (e.g. the metadata of Amazon dataset) to your processed dataset? It is more convenient for us to make comparisons with your great work!

**Comment by Re-bin** [comment]
Hi 👋

That's right. When utilizing the following codes to generate a profile, the instruction and input prompt will be concatenated into a specific format according to `gpt-3.5-turbo`.
```Python
def get_gpt_response_w_system(prompt):
    global system_prompt
    completion = openai.ChatCompletion.create(
        model='gpt-3.5-turbo',
        messages=[
            {"role": "system", "content": system_prompt}, # instruction
            {"role": "user", "content": prompt}, # input prompt
        ]
    )
    response = completion.choices[0].message.content
    return response
```
However, it's not expensive to process all the data, which only costs around 100 dollars.

**Don't worry**, we will provide the mapping dictionaries from the `user/item_id` to the `original id` (e.g., ASIN for the item in Amazon-book) within 2-3 days for our data. With these dictionaries, you can easily obtain the original meta information of users/items with the raw data :)

Best regards,
Xubin

**Comment by xmttttt** [comment]
Thanks for your assistance again!!!🤗🤗🤗
