### ISSUE TITLE
learning

### ISSUE THREAD

**Issue by Fengjie446** [HKUDS/RLMRec#5]
Hello, I am very interested in reading your article, but there are some issues in reproducing your experiment. The part mentioned in the article that combines with the large model in RLMRec-Con and RLMRec-Gen is not reflected in the running examples. I hope you can point it out to the students, which is very satisfying!

**Comment by Re-bin** [comment]
Hi 👋！

Thank you for your interest in RLMRec! In this work, Large Language Models (LLMs) are utilized to generate high-quality text descriptions, which are saved in `usr/itm_prf.pkl`, and then to encode text descriptions into semantic text embeddings, stored in `usr/itm_emb_np.pkl`. These operations can be performed as pre-processing steps before training the recommender models, hence the results are saved in pickle files for convenience.

During the training of RLMRec-Con and RLMRec-Gen, these text embeddings serve different purposes. For instance, in `lightgcn_plus.py`, the term `kd_loss` is used for contrastive learning, while in `lightgcn_gene.py`, the term `recon_loss` is used for reconstruction.

If you want to re-encode the text embeddings, you can refer to code provided in `generation/emb/generate_emb.py`. This code serves as a reference for encoding profiles to obtain text embeddings, using toy data as an example. The same process can be applied to the complete profiles saved in `usr/itm_prf.pkl`.

I hope you find this information helpful :)

Best regards,
Xubin
